In [54]:
#import numpy as np and check the version out
import numpy as np
print(np.__version__)

1.21.5


In [19]:
#create 1D array of numbers from 0 to 9
array_1=np.array([0,1,2,3,4,5,6,7,8,9])
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#create 3x3 numpy boolean array of all True's
array_ones= np.ones((3,3), dtype=bool)
array_ones

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
#create 3x3 numpy array of all False
array_zeros= np.zeros((3,3), dtype=bool)
array_zeros

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [23]:
#extract all odd numbers from the 1D array
array_1[array_1 % 2==1]

array([1, 3, 5, 7, 9])

In [25]:
#replace all odd numbers in arr with -1 in the 1D array
array_1[array_1 % 2==1]= -1
array_1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [28]:
#convert a 1D array to a 2D array with 2 rows
array_1.reshape(2,5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [30]:
#create 2D arrays a and b
np.random.seed(7688)
a= np.random.randint(10, size=(2,3))
b= np.random.randint(10, size=(2,3))
a, b

(array([[1, 4, 4],
        [9, 1, 9]]),
 array([[2, 2, 2],
        [9, 2, 5]]))

In [32]:
#stack arrays a and b verticaly
vertical= np.vstack((a,b))
vertical

array([[1, 4, 4],
       [9, 1, 9],
       [2, 2, 2],
       [9, 2, 5]])

In [34]:
#stack the arrays a and b horizontally
horizontal=np.hstack((a,b))
horizontal

array([[1, 4, 4, 2, 2, 2],
       [9, 1, 9, 9, 2, 5]])

In [38]:
#get the common items between a and b
np.intersect1d(a,b)

array([9])

In [39]:
#from array A remove all items present in array B
a= [item for item in a if item not in b]
a

[array([1, 4, 4])]

In [41]:
#create a 2D array and reverse the rows
np.random.seed(8832)
array_2d = np.random.randint(10,size=(3,2))
np.flip(array_2d, axis=0)

array([[3, 4],
       [5, 1],
       [3, 5]])

In [42]:
#reverse the column
np.flip(array_2d,axis=1)

array([[5, 3],
       [1, 5],
       [4, 3]])

In [44]:
#create a 2Darry of shape 5x3 to contain decimal numbers between 5 and 10
array =np.random.uniform(5,10, size=(5,3))
array

array([[5.80747702, 9.52435662, 6.42505659],
       [9.16130516, 6.2856908 , 8.53387446],
       [9.34892495, 7.92802005, 5.98808841],
       [8.75949691, 8.14426293, 9.81368852],
       [8.92422925, 9.1734434 , 9.45114862]])

In [45]:
#create a 2D array that print only 3 decimal places
np.round(array,3)

array([[5.807, 9.524, 6.425],
       [9.161, 6.286, 8.534],
       [9.349, 7.928, 5.988],
       [8.759, 8.144, 9.814],
       [8.924, 9.173, 9.451]])

In [46]:
#create a 1D array and limit the number of items printed to a maximum of 6 elements
another_array=np.arange(390)
np.set_printoptions(threshold=6)
another_array

array([  0,   1,   2, ..., 387, 388, 389])

In [47]:
#import 2 images and turn them to numerical values
from matplotlib.image import imread

   # <img src ='pictures/car-photo.png'>

   # <img src='pictures/panda.png'>

In [51]:
#when car image is converted to numerical value
car=imread('car-photo.png')
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [52]:
#when panda image is converted to numerical value
panda=imread('panda.png')
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0